### ISSUE TITLE
pylie and lie_pylie

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#70]
In the folder **MDStudio/components** there is the **lie_pylie** folder that contains the **pylie** package. 
When trying to run the main program, I run into the following issue:
```
~$ python MDStudio/
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/MDStudio/__main__.py", line 215, in <module>
    bootstrap_app(lie_cli(__rootpath__))
  File "/home/user/MDStudio/__main__.py", line 141, in bootstrap_app
    default_component_settings = components.component_settings()
  File "/home/user/MDStudio/components/lie_system/lie_system/component_manager.py", line 172, in component_settings
    if hasattr(self.get_component(component), 'settings'):
  File "/home/user/MDStudio/components/lie_system/lie_system/component_manager.py", line 196, in get_component
    component, [path, os.path.join(path, component)])
ImportError: No module named lie_pylie
```
The component manager search for tha names of the folders in the **components** but the package **pylie** is stored in the folder **lie_pylie**. We either change the name of the folder or the name of the library.

**Comment by marcvdijk** [comment]
I do not experience that problem working on master.
I did commit the name change from lie_pylie/lie_pylie to lie_pylie/pylie in master. You could have a look at that.

**Comment by felipeZ** [comment]
I also have the same folder name in the **prototype** branch *lie_pylie/pylie* but I still got the above error
