### ISSUE TITLE
crossbar container fails on starts

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/MDStudio#96]
This is the output of docker-compose logs
```
crossbar_1     | Loading .env environment variables…
crossbar_1     | Traceback (most recent call last):
crossbar_1     |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
crossbar_1     |     "__main__", mod_spec)
crossbar_1     |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
crossbar_1     |     exec(code, run_globals)
crossbar_1     |   File "./__main__.py", line 10, in <module>
crossbar_1     |     import pytz
crossbar_1     | ModuleNotFoundError: No module named 'pytz'
```

**Comment by felipeZ** [comment]
The problem is that none of the dependencies from the **__main__.py** file are installed
